### ISSUE TITLE
HBD is broken

### ISSUE THREAD

**Issue by skzap** [openhive-network/hive#6]
1 SBD will give me 1 HBD. So 1 dollar gets me 2 dollars.

Did you even think about that before thinking about giving 1 HBD to everyone? SBD is fucking debt, and your blockchain will start with 7M USD$ debt, including 3.5M USD$ inside the @upbitme account.

Economics is important for a blockchain.

**Comment by krischik** [comment]
Isn't that what happens whenever a blockchain splits?

**Comment by ShmoogleOsukami** [comment]
When the blockchain gets up and running it'll adjust the debt ratio and HBD emissions automatically based on the price of the peg. If it's $1 its fine if it's less it'll stop payout out HBD. 
The chain is a mirror of steem. we have the same amount of coins and the same amount of debt. 

Not paying 1SBD to 1HBD would result in people losing money and leave a bad taste in many users mouths.

**Comment by skzap** [comment]
@krischik I don't think it's comparable to the BTC/BCH fork. This chain did not have pegged assets running on it.

@ShmoogleOsukami You are right, there is even an option to convert in the chain, which uses the median price feed of the top 20 witnesses. It takes 3.5 days but you get 1 USD (real usd) worth of Hive / Steem.

Basically, Hive will start with 7M USD debt inherited from SBD. It's not a bug, but it will make both STEEM and Hive plumet in value. It also gives free money to SBD holders.

Not porting the SBD to HBD would have been a way better solution. People wouldn't have lost money since they would still have 1 SBD worth about 1 USD

**Comment by oriolpont** [comment]
Unless one believes in economic perpetuum mobiles, the value of one old-STEEM gets divided in one new-STEEM and one HIVE, `STEEM -> STEEM' + HIVE`. 

Now, the system has been for the most of these past months in haircut mode, which implies that SBD is clearly below 1 USD and instead dictated by the value of pre-fork STEEM. The most reasonable is to expect that `SBD -> SBD' + HBD`, which whatever (subdollar) value split proportionally.

Yes, if a miracle occured and both systems got out of haircut, that could imply a doubling from one dollar to two dollars, but hey, that would not be far from that other miracle of when SBD flied to $10 each :-D

**Comment by shawnpringle** [comment]
There are too many dollars on both chains.  There should be no more printing of dollars well before it gets to 10% of the combined value.  I think the best solution is to halt any production of new dollars and never print more dollars until the dollars make up less than 2.5% of the combined market cap.  If you read the papers, you only need to stop and the USD will catch up.

**Comment by krischik** [comment]
@shawnpringle Or easier: Don't print new dollars unless the coin is above one $ in real value for at least a week. Which both are not .

Much easy to understand rule.

**Comment by shawnpringle** [comment]
@krischik that's easier for us humans but the protocol doesn't see the price of Hive Dollars in terms of USD.  The only price feed it gets is the price of Hive in U.S. dollars.  So, we can only calculate things in terms of market cap.  Your idea would require another price feed to be set by witnesses, and if we don't keep proposals simple, we are more likely to just continue with the status quo.

The protocol gives up on protecting the dollar when it is at 10%.  Dollars shouldn't be printed at all after some value well before reaching that.

**Comment by oriolpont** [comment]
I propose to close this issue. Nearly one month on, SBD is out of haircut regime at trades at peg, whereas HBD is under moderate haircut (70% at current rates).

I would thus conclude that HBD is quite clearly **not** broken. Owners of pre-fork SBD did seem to have got a payday, mostly at the expense of STEEM and HIVE holders, as the massive rate of conversions and price declines would seem to suggest.

**Comment by shawnpringle** [comment]
Okay, I will leave aside that HBD and SBD are *different coins* for this
discussion because they are fundamentally the *same internally*.

However, I am **unable** to deposit or withdrawal from the exchanges that
publish these feeds.  If it is really parity, I can sell 100 SBD and get
nearly $100 worth of BTC with it, minus fees but this is not the case.  How
do I take custody of Steem Dollars not already in the exchanges?  But let's
put that aside as well.

What is different between Steem Dollars and Hive Dollars?  Steem Dollars
are locked up in the Steem DAO thanks to/due to Justin Sun.  Whereas in
Hive, Hive Dollars are flowing toward funding various projects involving
Hive.  In other words, Steem Dollars are not getting into hands of people
who sell these dollars.  Whereas in the case of Hive, they are going to
projects and getting sell pressure.  The Steem DAO has 5% of the Steem
Dollar supply.

The Steem DAO was able to accumulate the amount of Dollars to be able to
wreck the price, because the monetary policy of creating Steem Dollars in
quantities **the peg mechanism could never support**.  Printing should stop
before it reaches the 10% rate where the peg mechanism gives up.

So with both of these set aside, historically SBD has over the long haul
been well under a US dollar for most of its history.  Why?  The correction
mechanism only adds buy pressure when SBD looses its peg.  And unlike
something like oil, which people produce less of when the price is low, SBD
still gets printed even *after* the peg mechanism gives up.

**Comment by oriolpont** [comment]
@shawnpringle that is correct. The peg mechanisms are rather weak, they always had been. Vested stakeholders should (but are not forced to) restrict dao grants in times of haircut. 

Nevertheless, that issue already existed in pre-fork Steem and exists still in post-fork Steem too (steem.dao keeps piling up funds, even if they are currently not handed out to any grantees). It is only very tangentially related --if at all-- to the github issue being discussed here. If we are not rolling back the issuance of HBD, I insist that it can be closed.

**Comment by shawnpringle** [comment]
Did you want this issued again as a new issue because it doesn't match the
beginning thread?
